# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Hanlin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for Hanlin
pod 'JTCalendar', '~> 2.0'
pod 'ASIHTTPRequest'
pod 'CSLazyLoadController', '~> 1.0'

end
